"""Add simple wine batch model

Revision ID: a370e09fe716
Revises: 
Create Date: 2025-06-20 22:03:28.390311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a370e09fe716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wine_batches',
    sa.Column('batch_number', sa.String(length=50), nullable=False, comment='Unique batch identifier (e.g., ACEDIANO-2024-001)'),
    sa.Column('wine_name', sa.String(length=200), nullable=False, comment='Wine name (e.g., ACEDIANO Monastrell)'),
    sa.Column('producer', sa.String(length=200), nullable=False, comment='Wine producer/winery name'),
    sa.Column('total_bottles', sa.Integer(), nullable=False, comment='Total number of bottles in batch'),
    sa.Column('status', sa.Enum('ORDERED', 'AVAILABLE', 'SOLD_OUT', name='winebatchstatus'), nullable=False, comment='Current status of the batch'),
    sa.Column('total_cost_nok_ore', sa.Integer(), nullable=False, comment='Total cost in NOK øre (84000 = 840.00 NOK)'),
    sa.Column('target_price_nok_ore', sa.Integer(), nullable=True, comment='Target selling price per bottle in NOK øre'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key using UUID as string'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    comment='Simplified wine batch for initial migration'
    )
    op.create_index('idx_wine_batch_status', 'wine_batches', ['status'], unique=False)
    op.create_index(op.f('ix_wine_batches_batch_number'), 'wine_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_wine_batches_wine_name'), 'wine_batches', ['wine_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wine_batches_wine_name'), table_name='wine_batches')
    op.drop_index(op.f('ix_wine_batches_batch_number'), table_name='wine_batches')
    op.drop_index('idx_wine_batch_status', table_name='wine_batches')
    op.drop_table('wine_batches')
    # ### end Alembic commands ### 